Add open peer review course #186
OpenEnergyPlatform/examples pull request #196
Opened 2023-06-12 10:30 UTC by Ludee

### Added

- Add new open peer review course [(#196)](https://github.com/OpenEnergyPlatform/academy/pull/196)

2023-06-12 18:51 UTC, christian-rli commented on docs/courses/09_peer_review.md
> +Todo: Link to documentation of the badges
This TODO is still open

2023-06-12 18:52 UTC, christian-rli commented on docs/courses/09_peer_review.md
> +- Stephan's notes and thesis
Either add the mentioned notes or remove this line.

2023-06-12 18:54 UTC, christian-rli requested changes
Content and language of what's there is acceptable :) The course would benefit from one or more screenshots. If the development notes are removed from the file, it may go public as a first version.

2023-06-13 12:59 UTC, Ludee commented
I finished the two open tasks. Please review again!

2023-06-13 15:33 UTC, christian-rli approved these changes

2023-06-13 15:36 UTC, merged